services:
  rbay-db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=auction
    volumes:
      - db:/var/lib/mysql
  
  rbay-fr:
    image: ghcr.io/farzaddm/rbay-fr:latest
    ports:
      - 5173:80
    
  rbay-bk:
    image: ghcr.io/farzaddm/rbay-bk:latest
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - rbay-db

volumes:
  db:
